name:                jw-haskell-mal
version:             0.2.0.0
github:              "jw120/mal"
license:             BSD3
author:              "Joe Watson"
maintainer:          "joe_watson@mail.com"
copyright:           "2019 Joe Watson"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/jw-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- megaparsec
- mtl
- optparse-applicative
- readline
- text
- time

library:
  source-dirs: src

executables:
  mal:
    main:                mal.hs
    source-dirs:         app
    dependencies:
    - jw-haskell-mal
  step0_repl:
    main:                step0_repl.hs
    source-dirs:         app
    dependencies:
    - jw-haskell-mal
  step1_read_print:
    main:                step1_read_print.hs
    source-dirs:         app
    dependencies:
    - jw-haskell-mal

tests:
  mal-specs:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - jw-haskell-mal
    - hspec
    - hspec-megaparsec
