#!/bin/bash

# We use speci

cd $(dirname $0)

case ${STEP:-stepA_mal} in
    step0_repl)
        stack exec step0_repl "${@}"
        ;;
    step1_read_print)
        stack exec step1_read_print "${@}"
        ;;
    *)
        stack exec mal "${@}"
esac
