disabled_rules:
- identifier_name
opt_in_rules:
- anyobject_protocol
- array_init
- attributes
- closure_end_indentation
- closure_spacing
- collection_alignment
- contains_over_first_not_nil
- conditional_returns_on_newline
- discouraged_object_literal
- empty_count
- empty_string
- empty_xctest_method
- explicit_init
- fallthrough
- fatal_error_message
- file_header
- first_where
- force_unwrapping
- identical_operands
- implicit_return
- joined_default_parameter
- let_var_whitespace
- literal_expression_end_indentation
- legacy_random
- lower_acl_than_parent
- modifier_order
- multiline_arguments
- multiline_parameters
- nimble_operator
- number_separator
- operator_usage_whitespace
- overridden_super_call
- private_action
- private_outlet
- prohibited_super_call
- reduce_into
- redundant_nil_coalescing
- redundant_type_annotation
- single_test_class
- sorted_first_last
- sorted_imports
#- static_operator
- strict_fileprivate
- strong_iboutlet
- switch_case_on_newline
- toggle_bool
- trailing_closure
- unavailable_function
- unneeded_parentheses_in_closure_argument
- unused_import
- unused_private_declaration
- vertical_parameter_alignment_on_call
- yoda_condition
