#!/bin/bash

case $STEP in

    step0_repl )
	racket step0_repl.rkt "${@}"
	;;
    step1_read_print )
	racket ../jw-racket/src/step1_read_print.rkt "${@}"
	;;
    *)
	racket brmal/repl.rkt "${@}"
	;;
esac
