# Full set of rules here - disabling those that don't make sense in this
# non-OOP CLI ap
disabled_rules:
- cyclomatic_complexity
- file_length
- identifier_name
- large_tuple
- private_over_fileprivate
opt_in_rules:
- anyobject_protocol
- array_init
- attributes
- closure_body_length
- closure_end_indentation
- closure_spacing
- collection_alignment
- contains_over_first_not_nil
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_range_nil_comparison
# - conditional_returns_on_newline
- convenience_type
- discouraged_object_literal
- discouraged_optional_boolean
- discouraged_optional_collection
- empty_collection_literal
- empty_count
- empty_string
- empty_xctest_method
- enum_case_associated_values_count
- explicit_init
- explicit_acl
- explicit_enum_raw_value
- explicit_self
- explicit_top_level_acl
# - explicit_type_interface # Required types for var/let etc
- expiring_todo
#- extension_access_modifier
- fallthrough
- fatal_error_message
- file_header
# - file_name # should match a type in the file
- file_name_no_space
# - file_types_order
- first_where
- flatmap_over_map_reduce
- force_unwrapping
# - function_default_parameter_at_end
- identical_operands
- implicit_return
- implicitly_unwrapped_optional
- indentation_width
- joined_default_parameter
- last_where
- let_var_whitespace
- literal_expression_end_indentation
- legacy_multiple
- legacy_random
- lower_acl_than_parent
- missing_docs
- modifier_order
- multiline_arguments
- multiline_parameters
- multiline_arguments_brackets
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters_brackets
- nimble_operator
#- no_extension_access_modifier
- no_grouping_extension
- nslocalizedstring_key
- nslocalizedstring_require_bundle
- number_separator
- object_literal
- operator_usage_whitespace
- optional_enum_case_matching
- overridden_super_call
- override_in_extension
# - pattern_matching_keywords
- prefer_self_type_over_type_of_self
# - prefixed_toplevel_constant # Add k to top-level constant names
- private_action
- private_outlet
- prohibited_interface_builder
- prohibited_super_call
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- raw_value_for_camel_cased_codable_enum
- reduce_into
- redundant_nil_coalescing
- redundant_type_annotation
# - required_deinit
- required_enum_case
- single_test_class
- sorted_first_last
- sorted_imports
# - static_operator # Encouraged to make custom operators static in an extension
# - strict_fileprivate
- strong_iboutlet
- switch_case_on_newline
- toggle_bool
- trailing_closure
# - type_contents_order
- unavailable_function
- unowned_variable_capture
- untyped_error_in_catch
- unused_declaration
- unneeded_parentheses_in_closure_argument
- unused_import
- vertical_parameter_alignment_on_call
# - vertical_whitespace_between_cases # Vertical whitespace between cases
- vertical_whitespace_closing_braces
- vertical_whitespace_opening_braces
- xct_specific_matcher
- yoda_condition
